name: build-and-test
on: 
  push:

jobs:
  all:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false
          submodules: 'recursive'
            #- name: build docker
            #run: docker build -t final-project-build-container .
      - name: Ensure write permissions
        run: chmod -R 777 ${GITHUB_WORKSPACE}
      - name: run build
        run: |
          docker run --rm \
          -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
          -w ${GITHUB_WORKSPACE} \
          crops/yocto:ubuntu-24.04-base \
          bash -c "git config user.email 'action@github.com' && \
                   git config user.name 'GitHub Actions' && \
                   ./build.sh"


